### ISSUE TITLE
Switch Authentication over to new format

### ISSUE THREAD

**Issue by ThomasK81** [Brucheion/Brucheion#32]
Email from Github:
On August 6th, 2020 at 16:46 (UTC) your application (Brucheion) used an access token (with the User-Agent Go-http-client/1.1) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

**Comment by jankaszel** [comment]
fixed via https://github.com/Brucheion/Brucheion/commit/644691716ca347114e6962cf161d03d68ab13160 (has been fixed in goth [about a year ago](https://github.com/markbates/goth/commit/cbc28e456b52b2140adcafbb60db558bcb110798)).
