### ISSUE TITLE
Failing updates on Windows: locked executable

### ISSUE THREAD

**Issue by jankaszel** [Brucheion/Brucheion#51]
When updating Brucheion on Windows, the downloaded executable can't simply replace the running `Brucheion.exe` due to [file locking](https://stackoverflow.com/a/196908). Renaming the running executable to something like `Brucheion-v<version>.exe` could fix this (and successively removing that old binary when running the updated executable).

**Comment by ThomasK81** [comment]
That's a good idea. Let's do it like this!

**Comment by jankaszel** [comment]
Fixed via https://github.com/Brucheion/Brucheion/commit/e36f2bcc2b06c10eb39e3a4989a5c5458767f6b8.
