### ISSUE TITLE
Ability to change display from a landscape to portrait dynamically based on image size

### ISSUE THREAD

**Issue by martingluckman** [Brucheion/Brucheion#54]

**Comment by martingluckman** [comment]
1.Autodetect based on image width (is image portrait or landscape). if image is square then default to portrait.
2.With option for user to override in settings/UI

**Comment by PhMaas** [comment]
https://www.dropbox.com/s/8vi73apvm1dmm6u/C3D_57v.jpg?dl=0
https://www.dropbox.com/s/gxsueev7mfcfbp5/KuS_129_67ar.jpg?dl=0

**Comment by martingluckman** [comment]
Landscape example:

![image](https://user-images.githubusercontent.com/1072059/143414498-c4b870a0-3b00-43a1-864e-bfb6498ccb2e.png)

**Comment by martingluckman** [comment]
Portrait example:

![ViEtItwQ](https://user-images.githubusercontent.com/1072059/143414753-cbd4d8d2-c5a7-4211-b4e4-6702c52c5a30.jpeg)

**Comment by martingluckman** [comment]
Toggle button goes here:

![image](https://user-images.githubusercontent.com/1072059/143415140-af007d3b-5bcd-4eeb-8f21-9fe8ec92c74a.png)

Icon:

![image](https://user-images.githubusercontent.com/1072059/143415198-f1ac156d-b1fa-4c9c-b69f-8ed82e9a1dd1.png)

**Comment by martingluckman** [comment]
Multi User notes: Toggle feature is for admin or public.
