### ISSUE TITLE
Sketch of Brucheion Progress up to Dec 2022

### ISSUE THREAD

**Issue by PhMaas** [Brucheion/Brucheion#61]
Briefly describe which progress could be made in the first phase of the further development of Brucheion until Dec 2022,  in technical terms but in natural language, max. half a page. Please refer to section 2.3.1.7 of the application for the current phase of the project (phase 2). Urgently needed until March 27.
[Beschreibung_des_Vorhabens.pdf](https://github.com/Brucheion/Brucheion/files/8314797/Beschreibung_des_Vorhabens.pdf)

**Comment by kpreisendanz** [comment]
@martingluckman
