### ISSUE TITLE
Line number identification in transcript

### ISSUE THREAD

**Issue by PhMaas** [Brucheion/Brucheion#65]
2.3 Automatic identification of line numbers in the transcripts (manuscripts, printed  editions) in relation to the line numbers of the text in the corresponding images

**Comment by martingluckman** [comment]
@PhMaas please could you clarify the logic for identifying line numbers in the transcripts. Could you give some examples with screenshots here in this ticket. Thank you.

**Comment by PhMaas** [comment]
<img width="1320" alt="Screen Shot 2020-08-22 at 10 32 07" src="https://user-images.githubusercontent.com/23402118/220285995-7b291226-6139-4c96-837c-60e707162c85.png">
Line numbers should appear at the beginning of each line of the transcripts, specifying the line of the corresponding manuscript counted from top to bottom (1-9 on the example page). As for now, manuscript images will not have line numbers. The reader will count line numbers "manually." The implementation of the line-number feature  should not be too hard if line numbers are part of the passage identification in each transcript (in the example NBh 1.1.1_C3d_57r7) and an algorithm created that specifies the following lines of the respective passage with an increase of 1 per line.

**Comment by martingluckman** [comment]
Completed.
